repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: keycloak
    namespace: keycloak
    chart: bitnami/keycloak
    version: 14.4.0
    installed: true
    values:
      - values.yaml
