repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: cassandra
    namespace: cassandra
    chart: bitnami/cassandra
    version: 10.2.1
    installed: true
    values:
      - values.yaml