repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: elasticsearch
    namespace: elasticsearch
    chart: bitnami/elasticsearch
    version: 19.6.0
    installed: true
    values:
      - values.yaml