# Shrink default JVM heap.
esJavaOpts: "-Xmx128m -Xms128m"

# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "100m"
    memory: "512M"
  limits:
    cpu: "1000m"
    memory: "512M"

# Request smaller persistent volumes.
volumeClaimTemplate:
  resources:
    requests:
      storage: 1g

master:
  replicaCount: 1
data:
  replicaCount: 1
  resources:
    heapSize: "128m"
coordinating:
  replicaCount: 1
ingest:
  replicaCount: 1

ingress:
  enabled: true
  hostname: elasticsearch.k8s-aderevets-loc
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    kubernetes.io/ingress.class: nginx

global:
  kibanaEnabled: true

kibana:
  ingress:
    enabled: true
    tls: true
    hostname: kibana.k8s-aderevets-loc
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-staging"
      kubernetes.io/ingress.class: nginx
metrics:
  enabled: true
