repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: postgres
    namespace: postgres
    chart: bitnami/postgresql-ha
    version: 11.5.2
    installed: true
    values:
      - values.yaml